name: CI
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  rubocop:
    runs-on: ubuntu-latest
    env:
      BUNDLE_SMART_PROXY: '0'
    steps:
      - uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.5
          bundler-cache: true
      - name: Run rubocop
        run: bundle exec rubocop --format github
